// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zqcwmidydtpsfzlgykgb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpxY3dtaWR5ZHRwc2Z6bGd5a2diIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk1NzM0NDcsImV4cCI6MjA2NTE0OTQ0N30.PI8jpCXUE13dSb5cEnFJR_OxS2gjyJXttdS819a865s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);